import { UIButton } from './elements/Button.js';
import { UIChance } from './elements/Chance.js';
import { UICollection } from './elements/Collection.js';
import { UIColor } from './elements/Color.js';
import { UIDrag } from './elements/Drag.js';
import { UIDragButton } from './elements/DragButton.js';
import { UIElement } from './elements/Element.js';
import { UIFile } from './elements/File.js';
import { UIInput } from './elements/Input.js';
import { UIInputList } from './elements/InputList.js';
import { UIInputSearch } from './elements/InputSearch.js';
import { UIList } from './elements/List.js';
import { UIListStep } from './elements/ListStep.js';
import { UILabel } from './elements/Label.js';
import { UIModal } from './elements/Modal.js';
import { UINumber } from './elements/Number.js';
import { UINumberList } from './elements/NumberList.js';
import { UINumberRange } from './elements/NumberRange.js';
import { UINumberStep } from './elements/NumberStep.js';
import { UIPanel } from './elements/Panel.js';
import { UIRange } from './elements/Range.js';
import { UIRow } from './elements/Row.js';
import { UISection } from './elements/Section.js';
import { UISelect } from './elements/Select.js';
import { UISelectButton } from './elements/SelectButton.js';
import { UIText } from './elements/Text.js';
import { UIToggle } from './elements/Toggle.js';
import { UIToggleCheck } from './elements/ToggleCheck.js';
import { UIToggleGrid } from './elements/ToggleGrid.js';
import { UITree } from './elements/Tree.js';

const Elements = { UIChance, UIText, UIToggle, UIToggleCheck, UISelect, UISelectButton, UIRow, UISection, UINumberStep, UIPanel, UIRange, UINumberList, UINumberRange, UIModal, UINumber, UIListStep, UIList, UILabel, UIInputList, UIInput, UIFile, UIElement, UIDragButton, UIDrag, UIColor, UICollection, UIButton, UIToggleGrid, UIInputSearch, UITree };

export { Elements };